### ISSUE TITLE
Failure to build 0.4.3 from crate on Linux

### ISSUE THREAD

**Issue by smbolton** [norepimorphism/libui-ng-sys#1] opened 2022-05-19 04:20 UTC
I can successfully build 0.4.3 from a repo cloned from github, but the 0.4.3 crate downloaded from crates.io fails to build. Build environment is x86_64 Slackware Linux "-current" (15.0 with updates), and rust 1.59.0 stable.

This builds and runs successfully:
```
$ git clone https://github.com/norepimorphism/libui-ng-sys.git libui-ng-sys-git
$ cd libui-ng-sys-git
$ git submodule init
$ git submodule update
$ cargo run --example
```

This fails to build:
```
$ cargo download -x libui-ng-sys=0.4.3
$ cd libui-ng-sys-0.4.3
$ cargo run --example
```
with this error message:
```
   Compiling libui-ng-sys v0.4.3 (/home/smbolton/libui-ng-sys/libui-ng-sys-0.4.3)
error: failed to run custom build command for `libui-ng-sys v0.4.3 (/home/smbolton/libui-ng-sys/libui-ng-sys-0.4.3)`

Caused by:
  process didn't exit successfully: `/home/smbolton/libui-ng-sys/libui-ng-sys-0.4.3/target/debug/build/libui-ng-sys-732c964f7d9dd898/build-script-build` (exit status: 1)
  --- stderr
  Error: BuildLibui(BuildNinja(Python { out: Output { status: ExitStatus(unix_wait_status(256)), stdout: "bootstrapping ninja...\nwhen running:  \"./src/inline.sh\" kBrowsePy < ./src/browse.py > build/browse_py.h\n", stderr: "/bin/sh: line 1: ./src/inline.sh: Permission denied\nTraceback (most recent call last):\n  File \"/home/smbolton/libui-ng-sys/libui-ng-sys-0.4.3/target/debug/build/libui-ng-sys-bc9c9a35880c3ab4/out/ninja/configure.py\", line 465, in <module>\n    n.build(built('browse_py.h'), 'inline', src('browse.py'),\n  File \"/home/smbolton/libui-ng-sys/libui-ng-sys-0.4.3/target/debug/build/libui-ng-sys-bc9c9a35880c3ab4/out/ninja/configure.py\", line 169, in build\n    self._run_command(self._expand(cmd, local_vars))\n  File \"/home/smbolton/libui-ng-sys/libui-ng-sys-0.4.3/target/debug/build/libui-ng-sys-bc9c9a35880c3ab4/out/ninja/configure.py\", line 194, in _run_command\n    subprocess.check_call(cmdline, shell=True)\n  File \"/usr/lib64/python3.9/subprocess.py\", line 373, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command '\"./src/inline.sh\" kBrowsePy < ./src/browse.py > build/browse_py.h' returned non-zero exit status 126.\n" } }))
```

I believe the problem is that the crate does not preserve the execute permission on the ninja scripts (they are correct in the git repo):

```
$ ls -l {libui-ng-sys-git,libui-ng-sys-0.4.3}/dep/ninja/src/inline.sh 
-rw-r--r-- 1 smbolton smbolton 1307 Nov 29  1973 libui-ng-sys-0.4.3/dep/ninja/src/inline.sh
-rwxr-xr-x 1 smbolton smbolton 1307 May 18 20:52 libui-ng-sys-git/dep/ninja/src/inline.sh*
```

I actually discovered the problem while trying to build boing. Thanks for your work on both!

**Comment by norepimorphism** [comment] 2022-05-19 11:00
Thanks for the issue! I will look into this on my Linux machine later today.

**Comment by norepimorphism** [comment] 2022-05-20 01:24
I can reproduce the issue on my machine.

> I believe the problem is that the crate does not preserve the execute permission on the ninja scripts (they are correct in the git repo)

You are correct. A workaround for crates that depend on *libui-ng-sys* is to fetch from the Git repository rather than from *crates.io*:

```toml
[dependencies]
libui-ng-sys = { git = "https://github.com/norepimorphism/libui-ng-sys" }
```

However, that is untenable long-term, and it breaks SemVer. One possible solution is to re-fetch the submodules locally. I'm unsure of the performance cost, but in comparison to the total time required to build *libui-ng-sys*, it is likely insignificant.

**Comment by norepimorphism** [comment] 2022-05-20 11:40
This is fixed by b11c38c and f48afb3.

**Comment by smbolton** [comment] 2022-05-20 16:26
https://github.com/norepimorphism/libui-ng-sys/commit/b11c38c91601bc2debc23e3eec6a8758d5265b11 works on my system. Of course, the real test will be when you next publish the crate -- I'll give it a test then. Thanks!

**Comment by norepimorphism** [comment] 2022-05-20 16:40
Great! I'll publish a new version when I get home.

**Comment by norepimorphism** [comment] 2022-05-21 11:16
Nevermind, this actually doesn't work. As I just learned, Cargo doesn't retain any *.git* directories when constructing a package, so the package stored in *crates.io* is not a valid Git repository, and when the build script attempts to update the Ninja Git repository, it complains that no such repository exists.

Unfortunately, that was my least hacky solution to this problem. Another idea is, instead of including Ninja (and potentially *libui-ng* and Meson) as Git submodules, we could clone them in the build script. That approach works, but *docs.rs* will fail to generate documentation because it disables network access while building a crate.

I've exhausted my Git-related ideas at this point, so my last is simply to manually mark the *inline.sh* file as executable in the build script. I'll get started on a new commit, and I'll yank the previous crate from *crates.io*.

**Comment by norepimorphism** [comment] 2022-05-21 12:13
Crate version 0.4.5 works for me on Linux. Let me know if it's fixed on your end.

**Comment by smbolton** [comment] 2022-05-21 15:18
Yes, if I change boing to require libui-ng-sys==0.4.5, the whole thing builds OOTB for me. The libui-ng-sys 'basic' example as well.

I think your eventual workaround is actually a good one -- it is very simple, and since you've vendored the ninja source into your package, there isn't risk of it breaking (except when you intentionally update ninja, of course). I'd just make sure your CI has a Linux build. 

Thanks for your help!

**Comment by norepimorphism** [comment] 2022-05-21 15:52
Great! I guess it isn't a bad solution, but you're correct in that, if I update the Ninja submodule, changes may necessarily propagate to the build script as well. That doesn't bother me very much, though.

And, I actually don't use CI at the moment (and I haven't even written tests for *boing* yet), so I should probably get on that. ;)

**Closed** 2022-05-21 15:52 UTC
